### ISSUE TITLE
Size of ONIE?

### ISSUE THREAD

**Issue by tchandramohan** [opencomputeproject/onie#1014]
Hi Alex,

I have two questions: 

1. What is the size of the filesystem where ONIE is installed successfully on? 
(I did not find a concrete answer to this in the documentation)
(Not the iso file or demo NOS, but the size ONIE takes up for it's instalation)

2. The size of ONIE depends on the target as well. In that case, what is the size of ONIE on a x86 target & an armv8 target?

P.S: On this tutorial, [https://www.youtube.com/watch?v=p86mMKZqh4g], C Brune says the size of ONIE is 10 MB for a x86 target.

**Comment by ehdoyle** [comment]
Hi,
 I'd say about 10-20MB seems to be about right. It will vary some depending on the target you're building for, (since the versions of software components and tools used to build them are going to vary) and how you want to measure it ( size of the installer, space the installer asks for, space the binaries actually take up, etc ). If you need better resolution than that, the best way to know for your particular case is to build and run it, then measure in a way that makes sense for your application -  which I'm rather curious about. Given the storage capacities of most modern devices, I would think using 20MB would hardly be noticed.
 If you don't have that hardware handy, you can build and run the x86 and arm64 target machines if you have QEMU installed  and measure things that way (again ,the emulation environments come through for ease in prototyping), to get a better idea of what you would be in for.
 HTH

**Comment by tchandramohan** [comment]
Thank you! Closing this ticket.
